artifact_uri: file:///Y:/Webclues/mlflow/Fire_detection_artifacts/f1387c9e351a45f0aede9fb1573a2de1/artifacts
end_time: 1721369087456
entry_point_name: ''
experiment_id: '105222130270950090'
lifecycle_stage: active
run_id: f1387c9e351a45f0aede9fb1573a2de1
run_name: Fire_2
run_uuid: f1387c9e351a45f0aede9fb1573a2de1
source_name: ''
source_type: 4
source_version: ''
start_time: 1721368984224
status: 3
tags: []
user_id: HP
