artifact_location: file:///Y:/Webclues/mlflow/Fire_detection_artifacts
creation_time: 1721368260064
experiment_id: '105222130270950090'
last_update_time: 1721368260064
lifecycle_stage: active
name: Fire_detection
